### ISSUE TITLE
how unpack super.0.d7972dc6.img file?

### ISSUE THREAD

**Issue by qiurigao** [munjeni/super_image_dumper#2]
![2](https://user-images.githubusercontent.com/22121479/123957342-322e8580-d99b-11eb-8296-708d03ee5bb2.PNG)
![ofp](https://user-images.githubusercontent.com/22121479/123957345-335fb280-d99b-11eb-9be8-f657802fb7d6.PNG)

my device: realme gt qcom 888

**Comment by munjeni** [comment]
Its command line tool, you need to do things from windows command prompt! This is not forum and this is not an isue, please ask in forum further questions
