### ISSUE TITLE
[Q] Could it able to backup "data partition" exclude "/data/media (internal storage)" from android 10, 11 ?

### ISSUE THREAD

**Issue by Guang1234567** [munjeni/super_image_dumper#3]
Hello dev:

Could it able to backup&retore "data partition" exclude "/data/media (internal storage)" from android 10, 11 ?

Thanks.

**Comment by munjeni** [comment]
Sorry I don't know, I'm worked on this tool almost year-two ago, I simply forgot anything about it, do research please!

**Comment by Guang1234567** [comment]
> Sorry I don't know, I'm worked on this tool almost year-two ago, I simply forgot anything about it, do research please!
Get it.
Thanks your reply.
